FROM registry.fedoraproject.org/fedora-minimal:26

RUN microdnf install --setopt='tsflags=nodocs' krb5-workstation && \
    microdnf clean all

COPY krb5.conf /etc/krb5.conf

ENV KRB5_TRACE /proc/self/fd/1

CMD /usr/bin/bash
