FROM registry.fedoraproject.org/fedora-minimal:26

RUN microdnf install --setopt='tsflags=nodocs' krb5-server && \
    microdnf clean all

COPY krb5.conf /etc/krb5.conf

ENV KRB5_TRACE /proc/self/fd/1

RUN kdb5_util -P masterkey create -s && \
    kadmin.local -q "addprinc -pw password HTTP/httpd.example.com@EXAMPLE.COM" && \
    kadmin.local -q "addprinc -pw password user@EXAMPLE.COM"

EXPOSE 88

CMD ["krb5kdc", "-n"]
